install:
  - cmd: mkdir release
  - cmd: cp C:\msys64\mingw32\bin\{zlib1.dll,libbz2-1.dll} release"
  - cmd: ls C:\MinGW\bin\
  - cmd: C:\msys64\usr\bin\pacman.exe -S --noconfirm liblzma 
  - cmd: cp C:\MinGW\bin\{liblzma-5.dll} release"
  - cmd: dsfsdf

  - set QTDIR=C:\Qt\5.8\mingw53_32
  - choco install -y InnoSetup
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin;%PATH%;"C:\Program Files (x86)\Inno Setup 5"
build_script:
  - qmake FastQt.pro
  - mingw32-make
after_build:
  - windeployqt release/fastqt.exe
  - cmd: cp C:\MinGW\bin\{zlib1.dll} release"
  - cmd: cp win32/KArchive/lib/libKF5Archive.dll.a release"
  - cmd: cp win32/KArchive/bin/libKF5Archive.dll release"
  - iscc innosetup.iss

artifacts:
  - path: Output\fastqt-*.exe
