branches:
  only:
    - master
    - devel
    - bamtools_dep

install:
  - set QTDIR=C:\Qt\5.8\mingw53_32
  - choco install -y InnoSetup
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin;%PATH%;"C:\Program Files (x86)\Inno Setup 5"
  # Install a recent cmake
  - set CMAKE_URL="https://cmake.org/files/v3.7/cmake-3.7.2-win64-x64.zip"
  - appveyor DownloadFile %CMAKE_URL% -FileName cmake.zip
  - 7z x cmake.zip -oC:\projects\deps > nul
  - move C:\projects\deps\cmake-* C:\projects\deps\cmake # Move to a version-agnostic directory
  - set PATH=C:\projects\deps\cmake\bin;%PATH%
  - cmake --version

build_script:
  # build bamtools
  - set Path=C:\MinGW\bin;%Path%
  - git submodule init
  - git submodule update
  - cd bamtools
  - dir
  - md build
  - cd build
   - cmake .. -DCMAKE_INSTALL_PREFIX=..\bamtools -G "Ninja" -DCMAKE_C_COMPILER="C:\MinGW\bin\mingw32-gcc.exe" -DCMAKE_CXX_COMPILER="C:\MinGW\bin\mingw32-g++.exe" -DCMAKE_MAKE_PROGRAME="C:\MinGW\bin\mingw32-make.exe"
  - dir 
  - ninja
  - cd ..\..
  # build fastqt
  - qmake FastQt.pro
  - mingw32-make
after_build:
  - windeployqt release/fastqt.exe
  - cmd: cp win32/KArchive/lib/libKF5Archive.dll.a release"
  - cmd: cp win32/KArchive/bin/libKF5Archive.dll release"
  - cmd: cp win32/zlib1.dll release"
  - cmd: cp win32/liblzma-5.dll release"
  - cmd: cp win32/libbz2-1.dll release"
  - cmd: cp LICENSE release/LICENSE.txt"
  - iscc innosetup.iss
  - rm release/*.o
  - rm release/*.cpp

artifacts:
  - path: Output\fastqt-*.exe
  - path: release
    type: zip
