branches:
  only:
    - master
    - devel
    - bamtools_dep

install:
  - set QTDIR=C:\Qt\5.8\mingw53_32
  - choco install -y InnoSetup
  - choco install -y cmake
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin;%PATH%;"C:\Program Files (x86)\Inno Setup 5";"C:\Program Files\CMake\bin"
  - dir "C:\Qt\Tools\mingw530_32\bin"

build_script:
  # build bamtools
  - set Path=C:\MinGW\bin;%Path%
  - git submodule init
  - git submodule update
  - cd bamtools
  - dir
  - md build
  - cd build
  - cmake.exe -G "NMake Makefiles" -DCMAKE_INSTALL_PREFIX=..\bamtools -DCMAKE_C_COMPILER=C:\Qt\Tools\mingw530_32\bin\gcc.exe -DCMAKE_CXX_COMPILER=C:\Qt\Tools\mingw530_32\bin\g++.exe ..
  - make install
  - cd ..\..
  # build fastqt
  - qmake FastQt.pro
  - mingw32-make
after_build:
  - windeployqt release/fastqt.exe
  - cmd: cp win32/KArchive/lib/libKF5Archive.dll.a release"
  - cmd: cp win32/KArchive/bin/libKF5Archive.dll release"
  - cmd: cp win32/zlib1.dll release"
  - cmd: cp win32/liblzma-5.dll release"
  - cmd: cp win32/libbz2-1.dll release"
  - cmd: cp LICENSE release/LICENSE.txt"
  - iscc innosetup.iss
  - rm release/*.o
  - rm release/*.cpp

artifacts:
  - path: Output\fastqt-*.exe
  - path: release
    type: zip
