language: cpp
dist: trusty
compiler: g++
sudo: required

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt57-trusty -y
  - sudo apt-get update
  - sudo apt-get install qt57base qt57charts-no-lgpl
  - sudo sh /opt/qt57/bin/qt57-env.sh 

install:
  - qmake FastQt.pro 
  - make 