language: cpp
dist: trusty
compiler: g++
sudo: required

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt58-trusty -y
  - sudo apt-get update

install:
  - sudo apt-get install qt58base qt58svg qt58charts-no-lgpl
  - source /opt/qt58/bin/qt58-env.sh


script:
  - git clone git://anongit.kde.org/extra-cmake-modules
  - cd extra-cmake-modules
  - mkdir build && cd build    
  - cmake .. -DCMAKE_INSTALL_PREFIX=/usr/
  - make && sudo make install
  - cd ../..
  - git clone git://anongit.kde.org/karchive.git
  - cd karchive
  - mkdir build && cd build 
  - cmake .. -DCMAKE_INSTALL_PREFIX=/usr/
  - make 
  - sudo make install
  - cd ../..
  - /opt/qt58/bin/qmake 
  - make 

# For gitter 
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/de567d4879b8b044dfe7
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
branches:
  only:
    - master 
